# Generated by Django 3.2.3 on 2021-07-16 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_alter_additem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='delete_item',
            field=models.BooleanField(default=False),
        ),
    ]
