# Generated by Django 3.2.3 on 2021-07-16 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_additem_delete_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='delete_item',
        ),
    ]
